#!/bin/bash

# Set up variables
ext1=""
ext2=""
source_dir=""
dest_dir=""

# Parse command line options
while getopts ":e:s:d:" opt; do
  case $opt in
    e)
      ext1=$OPTARG
      ext2=$OPTARG
      ;;
    s)
      source_dir=$OPTARG
      ;;
    d)
      dest_dir=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

# Check if variables are set
if [ -z "$ext1" ] || [ -z "$ext2" ] || [ -z "$source_dir" ] || [ -z "$dest_dir" ]; then
  # Print message to console
  echo "Variables are not set, asking you to provide them"
  # Prompt user to enter values for variables
  read -p "Enter value for ext1: " ext1
  read -p "Enter value for ext2: " ext2
  read -p "Enter value for source_dir: " source_dir
  read -p "Enter value for dest_dir: " dest_dir
fi

# Function to extract date and time from filename
extract_datetime() {
  # Print value of filename variable
  echo "Filename: $filename"
  # Use regex to extract date and time from filename
  if [[ $filename =~ ^([0-9]{4})([0-9]{2})([0-9]{2})_([0-9]{2}):([0-9]{2}):([0-9]{2})\.([^.]+)$ ]]; then
    year=${BASH_REMATCH[1]}
    month=${BASH_REMATCH[2]}
    day=${BASH_REMATCH[3]}
    hour=${BASH_REMATCH[4]}
    minute=${BASH_REMATCH[5]}
    second=${BASH_REMATCH[6]}
  else
    # Print error message if regex does not match
    echo "Error: Unable to extract date and time from filename"
    return 1
  fi
}


# Function to construct destination path
construct_path() {
  # Extract date and time from filename
  extract_datetime
  if [ $? -eq 0 ]; then
    # Construct destination path using date and time from filename
    dest_path="$dest_dir/$year/${year:2:2}-$month/$year-$month-$day"
    # Print value of dest_path variable
    echo "Destination path: $dest_path"
  else
    # Print error message if unable to extract date and time from filename
    echo "Error: Unable to construct destination path"
    return 1
  fi
}

# Iterate over files in source directory
for file in "$source_dir"/*; do
  filename=$(basename "$file")
  extension="${filename##*.}"
  # Check if file is of correct type
  if [ "$extension" == "$ext1" ] || [ "$extension" == "$ext2" ]; then
    # Construct destination path
    construct_path
    if [ $? -eq 0 ]; then
      # Check if destination directory exists
      if [ ! -d "$dest_path" ]; then
        # Create destination directory if it does not exist
        mkdir -p "$dest_path"
      fi
      # Move file to destination directory
      mv "$file" "$dest_path/$filename"
      # Print success message
      echo "Success: Moved $filename to $dest_path"
    fi
  fi
done
